#!/bin/sh
set -e


case "$1" in
    configure)

        SERVICE_NAME="kmagent"

        # Enable and start the service
        if [ -x "/bin/systemctl" ]; then
        # installing the kmagent
            echo "[STAGE 1]: Installing as service"
            $SERVICE_NAME install 

        # reloading the systemctl after installing kmagent service
            echo "[STAGE 2]: reloading systemctl daemon"
            systemctl daemon-reload || true

        # enabling the aggent via systemctl
            echo "[STAGE 3]: enabling via systemctl"
            systemctl enable $SERVICE_NAME || true

        # starting the service
            echo "[STAGE 4]: starting the service"
            systemctl start $SERVICE_NAME || true
        fi

        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        # Do nothing
        ;;
esac

exit 0