apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapDeploymentName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- toYaml .Values.configMapDeploymentLabels | nindent 4 }}
data:
  # The key here will become the filename inside the mountPath.
  # We name it exactly "agent.config.yaml" so it appears as such.
  agent-deployment.yaml: |

    receivers:
      otlp:
        protocols:
          grpc: 
            endpoint: '0.0.0.0:4317'
          http:
            endpoint: '0.0.0.0:4318'
      k8s_cluster:
        auth_type: serviceAccount
        node_conditions_to_report:
          - Ready
          - MemoryPressure
        allocatable_types_to_report:
          - cpu
          - memory
        metrics:
          k8s.container.cpu_limit:
            enabled: true
        resource_attributes:
          container.id:
            enabled: true
    processors:
      batch:
        send_batch_size: 10000
        timeout: 10s
    exporters:
      debug:
        verbosity: detailed
      otlphttp:
        endpoint: {{ .Values.COLLECTOR_ENDPOINT | default "https://otel.kloudmate.com:4318" }}
        headers:
          Authorization: {{ .Values.API_KEY }}
    service:
      pipelines:
        traces:
          receivers:
            - otlp
          processors:
            - batch
          exporters:
            - debug
            - otlphttp
        metrics:
          receivers:
            - otlp
            - k8s_cluster
          processors:
            - batch
          exporters:
            - debug
            - otlphttp
        logs:
          receivers:
            - otlp
          processors:
            - batch
          exporters:
            - debug
            - otlphttp
