{{- if .Values.featuresEnabled.apm -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.polylangDetectorDaemonsetName }}
  namespace: km-agent
  labels:
    {{- toYaml .Values.daemonsetLabels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.daemonsetLabels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.daemonsetLabels | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: polylang-detector
        image: "{{ .Values.polylangDetector.image.repository }}:{{ .Values.polylangDetector.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.polylangDetector.image.pullPolicy }}
        env:
          - name: KM_SVC_ACCOUNT_NAME
            value: {{ .Values.serviceAccountName }}
          - name: KM_CFG_UPDATER_RPC_ADDR
            value: {{ printf "cfg-updater-rpc-svc.km-agent.svc.cluster.local:%s" (.Values.KM_CFG_UPDATER_RPC_ADDR | toString) }}
          - name: KM_NODE_NAME
            valueFrom:
              fieldRef:
                # This field path directly exposes the name of the node
                # where the pod has been scheduled.
                fieldPath: spec.nodeName
{{- end }}