# This config file will be used by the KM-Agent on it's first initialization in docker mode.
receivers:
  filelog:
    include:
      - /var/log/**/*.log
      - /var/lib/docker/containers/**/*.log*
      - ${env:FILELOG_PATHS}
    exclude:
      - /var/log/kmagent*/**/*.log
      - '**/*.gz'
      - '**/*.zip'
      - '**/*.tar'
      - '**/*.xz'
      - '**/.*'
      - '**/*.tmp'
      - '**/*~'
    include_file_name_resolved: true
    include_file_path: true
    include_file_path_resolved: true
    max_log_size: "1MiB"

  docker_stats:
    endpoint: "unix:///var/run/docker.sock"
    collection_interval: 60s
    timeout: 10s

  hostmetrics:
    collection_interval: 60s
    root_path: /hostfs
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
      disk:
      network:
      filesystem:
        include_virtual_filesystems: true
        exclude_fs_types:
          fs_types:
            - autofs
            - binfmt_misc
            - bpf
            - cgroup
            - cgroup2
            - configfs
            - debugfs
            - devpts
            - devtmpfs
            - fusectl
            - hugetlbfs
            - iso9660
            - mqueue
            - nsfs
            - overlay
            - proc
            - procfs
            - pstore
            - rpc_pipefs
            - securityfs
            - selinuxfs
            - squashfs
            - sysfs
            - tracefs
          match_type: strict
        exclude_mount_points:
          mount_points:
            - /dev/*
            - /proc/*
            - /sys/*
            - /snap/*
            - /var/lib/docker/*
            - /var/lib/containerd/*
            - /var/lib/kubelet/*
            - /run/containerd/*
            - /run/k3s/*
            - /run/credentials/*
            - /run/user/*
          match_type: regexp
      load:
        cpu_average: true
  otlp:
    protocols:
      grpc:
      http:

exporters:
  debug:
    verbosity: basic
  otlphttp:
    sending_queue:
      enabled: true
      num_consumers: 10 # Increase to process more items in parallel
      queue_size: 10000 # Increase queue size to handle bursts
    endpoint: ${env:KM_COLLECTOR_ENDPOINT}
    headers:
      Authorization: ${env:KM_API_KEY}

processors:
  batch:
    send_batch_size: 10000
    timeout: 30s
  resourcedetection:
    detectors: [env, system, docker]
    override: false
  resource:
    attributes:
      - key: service.name
        action: insert
        from_attribute: host.name
  cumulativetodelta:
    include:
      match_type: strict
      metrics:
        - system.network.io
        - system.disk.io
        - system.disk.operations.rate
        - system.network.packets.rate
        - system.network.errors.rate
        - system.network.dropped.rate
  deltatorate:
    metrics:
      - system.network.io
      - system.disk.io
      - system.disk.operations.rate
      - system.network.packets.rate
      - system.network.errors.rate
      - system.network.dropped.rate
  transform/ratecalculation/copymetric:
    error_mode: ignore
    metric_statements:
      - context: metric
        statements:
          - copy_metric(name="system.network.io.rate") where metric.name == "system.network.io"
          - copy_metric(name="system.disk.io.rate") where metric.name == "system.disk.io"
          - copy_metric(name="system.disk.operations.rate") where metric.name == "system.disk.operations"
          - copy_metric(name="system.network.packets.rate") where metric.name == "system.network.packets"
          - copy_metric(name="system.network.errors.rate") where metric.name == "system.network.errors"
          - copy_metric(name="system.network.dropped.rate") where metric.name == "system.network.dropped"
  transform/ratecalculation/sumtogauge:
    error_mode: ignore
    metric_statements:
      - context: metric
        statements:
          - convert_sum_to_gauge() where metric.name == "system.network.io"
          - convert_sum_to_gauge() where metric.name == "system.disk.io"
          - convert_sum_to_gauge() where metric.name == "system.disk.operations"
          - convert_sum_to_gauge() where metric.name == "system.network.packets"
          - convert_sum_to_gauge() where metric.name == "system.network.errors"
          - convert_sum_to_gauge() where metric.name == "system.network.dropped"

extensions:

service:
  pipelines:
    metrics:
      receivers: [hostmetrics, docker_stats]
      processors: [resourcedetection, resource, cumulativetodelta, deltatorate, transform/ratecalculation/sumtogauge, transform/ratecalculation/copymetric, batch]
      exporters: [otlphttp, debug]
    logs:
      receivers: [filelog]
      processors: [resourcedetection, resource, batch]
      exporters: [otlphttp, debug]
