replicaCount: 1

# KloudMate platform specific arguments
API_KEY:
COLLECTOR_ENDPOINT: https://otel.kloudmate.com:4318
KM_UPDATE_ENDPOINT: https://api.kloudmate.com/agents/config-check
KM_CONFIG_CHECK_INTERVAL: 30s

# names of components to be installed.
clusterName: km-cluster
daemonsetName: km-agent-daemonset
deploymentName: km-agent-deployment
clusterRoleName: km-agent-cluster-role
agentServiceName: km-agent-svc
configUpdaterName: km-agent-config-updater
serviceAccountName: km-agent-sa
clusterRoleBindingName: km-agent-cluster-role-binding 
instrumentationCrdName: km-agent-instrumentation-crd
configMapDaemonsetName: km-agent-configmap-daemonset
configMapDeploymentName: km-agent-configmap-deployment 
polylangDetectorDaemonsetName: km-agent-polylang-detector-daemonset 

autoMountServiceAccount: true
autoCreateServiceAccount: true

monitoredNamespaces:
  - "default"

featuresEnabled:
  apm: true
  logs: true
  metrics: true
  traces: true

# image settings for kube agent
image:
  repository: ghcr.io/kloudmate/km-kube-agent
  pullPolicy: Always
  tag: "latest"

# image settings for config updater
configUpdater:
  image:
    repository: ghcr.io/kloudmate/km-kube-updater
    pullPolicy: Always
    tag: "latest"

# image settings for polylang-detector
polylangDetector:
  image:
    repository: ghcr.io/kloudmate/polylang-detector
    pullPolicy: Always
    tag: "latest"

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

podLabels: {}

# ----------- Labels ------------

# Below anotation is injected to all the Pods/ Namespaces & Nodes instrumented by the agent.
# This can be easily modified to add custom annotations from the KloudMate Dashboard
# instrumentation.kloudmate.com: criticality=high,sla-level=99.9,status=instrumented,managed-by=KloudMate

# Labels for the DaemonSet, which acts as a node-level agent.
daemonsetLabels:
  app.kubernetes.io/name: "km-kube-agent"
  app.kubernetes.io/instance: "km-kube-agent-daemonset"
  app.kubernetes.io/component: "node-agent"
  app.kubernetes.io/part-of: "kloudmate-platform"
  app.kubernetes.io/managed-by: "Helm"
  environment: "production"
  product: "kloudmate"

# Labels for the Deployment, which acts as a cluster-level agent.
deploymentLabels:
  app.kubernetes.io/name: "km-kube-agent"
  app.kubernetes.io/instance: "km-kube-agent-deployment"
  app.kubernetes.io/component: "cluster-agent"
  app.kubernetes.io/part-of: "kloudmate-platform"
  app.kubernetes.io/managed-by: "Helm"
  environment: "production"
  product: "kloudmate"

# Labels for the Config Updater.
configUpdaterLabels:
  app.kubernetes.io/name: "km-kube-agent"
  app.kubernetes.io/instance: "km-kube-agent-config-updater"
  app.kubernetes.io/part-of: "kloudmate-platform"
  app.kubernetes.io/managed-by: "Helm"
  product: "kloudmate"


# Labels for the Service Account.
serviceAccountLabels:
  app.kubernetes.io/name: "km-kube-agent"
  app.kubernetes.io/instance: "km-kube-agent-sa"
  app.kubernetes.io/part-of: "kloudmate-platform"
  app.kubernetes.io/managed-by: "Helm"
  product: "kloudmate"

# Labels for the Cluster Role.
clusterRoleLabels:
  app.kubernetes.io/name: "km-kube-agent"
  app.kubernetes.io/instance: "km-kube-agent-clusterrole"
  app.kubernetes.io/part-of: "kloudmate-platform"
  app.kubernetes.io/managed-by: "Helm"
  product: "kloudmate"

# Labels for the Cluster Role Binding.
clusterRoleBindingLabels:
  app.kubernetes.io/name: "km-kube-agent"
  app.kubernetes.io/instance: "km-kube-agent-clusterrolebinding"
  app.kubernetes.io/part-of: "kloudmate-platform"
  app.kubernetes.io/managed-by: "Helm"
  product: "kloudmate"

# Labels for the Instrumentation CRD.
instrumentationCrdLabels:
  app.kubernetes.io/name: "km-kube-instrumentation"
  app.kubernetes.io/instance: "km-kube-instrumentation-crd"
  app.kubernetes.io/part-of: "kloudmate-platform"
  app.kubernetes.io/managed-by: "Helm"
  product: "kloudmate"

# Labels for the Service.
serviceLabels:
  app.kubernetes.io/name: "km-kube-agent"
  app.kubernetes.io/instance: "km-kube-agent-service"
  app.kubernetes.io/part-of: "kloudmate-platform"
  app.kubernetes.io/managed-by: "Helm"
  product: "kloudmate"

# Labels for the Deployment ConfigMap.
configMapDeploymentLabels:
  app.kubernetes.io/name: "km-kube-agent"
  app.kubernetes.io/instance: "km-kube-agent-config-deployment"
  app.kubernetes.io/part-of: "kloudmate-platform"
  app.kubernetes.io/managed-by: "Helm"
  product: "kloudmate"

# Labels for the Daemonset ConfigMap.
configMapDaemonsetLabels:
  app.kubernetes.io/name: "km-kube-agent"
  app.kubernetes.io/instance: "km-kube-agent-config-daemonset"
  app.kubernetes.io/part-of: "kloudmate-platform"
  app.kubernetes.io/managed-by: "Helm"
  product: "kloudmate"

# Labels for the Namespace
NamespaceLabels:
  app.kubernetes.io/name: "km-agent"
  app.kubernetes.io/instance: "km-agent-namespace"
  app.kubernetes.io/part-of: "kloudmate-platform"
  app.kubernetes.io/managed-by: "Helm"
  product: "kloudmate"


# ----------- Operator ------------
opentelemetry-operator:
  crds:
    # Set to 'false' if you are managing CRDs externally, or 'true' to let the operator manage them.
    # The current setting 'true' is fine, but double-check your installation strategy.
    create: true
  enabled: true
  admissionWebhooks:
    create: true
    servicePort: 443
    pods:
      failurePolicy: Fail
    namePrefix: ""
    timeoutSeconds: 10
    namespaceSelector: {}
    objectSelector: {}
    certManager:
      enabled: false

    ## certManager must be disabled and autoGenerateCert must be enabled.
    ## If true and certManager.enabled is false, Helm will automatically create a self-signed cert and secret.
    autoGenerateCert:
      enabled: true
      recreate: true
      certPeriodDays: 365  
  manager:
    resources: {}
    autoInstrumentationImage:
      nodejs:
        repository: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs
        tag: latest
      java:
        repository: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java
        tag: latest
      python:
        repository: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python
        tag: latest
      dotnet:
        repository: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet
        tag: latest

# ----------- cert-manager ------------
cert-manager:
  enabled: false
  crds:
    enabled: false
    keep: true