name: Publish host agent image to the registry

on:
  release:
    types: [created]

jobs:
  build_and_pub:
    runs-on: ubuntu-latest
    steps:
      # Extract version from the release tag name
      - name: Determine Version
        id: get_version
        run: |
          VERSION_NUMBER=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          echo "Using release tag version: $VERSION_NUMBER"
          echo "VERSION=$VERSION_NUMBER" >> $GITHUB_ENV

      - uses: actions/checkout@v4
      - name: Build & Push Image
        run: |
          docker login --username kloudmate --password ${{ secrets.GHCR_PAT }} ghcr.io
          docker build . --build-arg VERSION=${{ env.VERSION }} \
            --tag ghcr.io/kloudmate/km-agent:${{ env.VERSION }} \
            --tag ghcr.io/kloudmate/km-agent:latest
          docker push ghcr.io/kloudmate/km-agent:${{ env.VERSION }}
          docker push ghcr.io/kloudmate/km-agent:latest