name: Publish kubernetes config updater image to the registry

on:
  release:
    types: [created]

permissions:
  contents: read
  packages: write

jobs:
  build_and_pub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: kloudmate # we may use a specific user in future releases i.e - ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # extract metadata (tags, labels) for the Docker image
      # this automatically generates tags and labels from the Git context and GitHub events.
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/kloudmate/km-kube-updater
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest

      # builds the image, tags it with the metadata from the previous step, and pushes it to the registry.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./updater.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Pass the release version and commit SHA as build arguments.
          build-args: |
            VERSION=${{ github.ref_name }}
            COMMIT_SHA=${{ github.sha }}

